# Z:\Main\github-repos\gardening_app\backend\app\main.py
# Standard FastAPI imports for creating API endpoints and handling HTTP exceptions
from fastapi import FastAPI, APIRouter, HTTPException, Depends
# CORS middleware to allow frontend-backend communication
from fastapi.middleware.cors import CORSMiddleware
# Import the router from plant_router.py which contains additional plant endpoints
from app.routers.plant_router import router as plant_router

# SQLAlchemy imports for database operations
from sqlalchemy.orm import Session
# Pydantic for data validation and serialization
from pydantic import BaseModel
# Python typing for type hints
from typing import List

# Import our local modules
from app import models                    # Contains SQLAlchemy database models
from app import database                  # Database connection setup
from app.database import engine          # SQLAlchemy engine for database operations

# Initialize the database tables
# This creates all tables defined in models.py if they don't exist
# Note: In production, you typically want to use proper migrations instead
models.Base.metadata.create_all(bind=engine)

# Create the main FastAPI application instance
# This is the core of our API
app = FastAPI(
    title="Gardening App API",
    description="API for managing garden plants",
    version="1.0.0"
)

# Configure CORS (Cross-Origin Resource Sharing)
# This is crucial for allowing our React frontend to communicate with the API
app.add_middleware(
    CORSMiddleware,
    # List of allowed origins (frontend URLs that can access our API)
    allow_origins=["http://localhost:3000"],  
    # Allow cookies and authentication headers
    allow_credentials=True,
    # Allow all HTTP methods (GET, POST, PUT, DELETE, etc.)
    allow_methods=["*"],                      
    # Allow all HTTP headers in requests
    allow_headers=["*"],                      
)

# Database Session Dependency
# This function creates a new database session for each request
# and ensures it's properly closed when the request is complete
def get_db():
    db = database.SessionLocal()  # Create new database session
    try:
        yield db                  # Yield the session to be used in the request
    finally:
        db.close()               # Ensure the session is closed after the request

# Pydantic model for API responses
# This model includes the ID field and is used for sending data back to clients
class Plant(BaseModel):
    name: str
    description: str
    id: int  # Auto-generated by database

    class Config:
        # Enable ORM mode to work with SQLAlchemy models
        # This allows Pydantic to convert SQLAlchemy models to JSON
        orm_mode = True

# Pydantic model for API requests
# This model excludes the ID field since it's generated by the database
class PlantCreate(BaseModel):
    name: str
    description: str

# Root endpoint for API health check
@app.get("/")
async def root():
    """
    Root endpoint to verify API is running
    Returns basic API information and links
    """
    return {
        "status": "online",
        "message": "Welcome to the Gardening App API",
        "docs_url": "/docs",  # Link to API documentation
        "openapi_url": "/openapi.json"  # Link to OpenAPI schema
    }

# Include the plant_router from plant_router.py with prefix
# This adds all routes from plant_router.py under the /api/v1 prefix
# The routes will show up in the Swagger docs under the "plants" tag
app.include_router(
    plant_router,
    prefix="/api/v1",  # This prefix should match the one in frontend API_BASE_URL
    tags=["plants"]
)

# Integration with plant_router.py:
# 1. plant_router.py contains additional plant-related endpoints (like PUT endpoints)
# 2. Those endpoints are mounted under /api/v1 (e.g., /api/v1/plants/id/{plant_id})
# 3. Both files share the same database session dependency (get_db)
# 4. Both files use the same SQLAlchemy models from models.py
# 5. The endpoints from both files will appear in the Swagger docs